-- Matches your current Supabase tables from the schema visualizer.
-- Run this in Supabase SQL Editor after confirming your existing columns.

create table if not exists public.users (
  id uuid primary key references auth.users(id) on delete cascade,
  full_name text not null,
  email text not null,
  created_at timestamptz not null default now()
);

create table if not exists public.expenses (
  id bigint generated by default as identity primary key,
  user_id uuid not null references public.users(id) on delete cascade,
  amount numeric(12, 2) not null check (amount > 0),
  category text not null,
  description text not null default '',
  expense_date date not null,
  created_at timestamptz not null default now()
);

create table if not exists public.budgets (
  id bigint generated by default as identity primary key,
  user_id uuid not null references public.users(id) on delete cascade,
  budget_amount numeric(12, 2) not null check (budget_amount >= 0),
  created_at timestamptz not null default now()
);

alter table public.users enable row level security;

alter table public.expenses enable row level security;
alter table public.budgets enable row level security;

drop policy if exists "Users can read their own profile" on public.users;
drop policy if exists "Users can insert their own profile" on public.users;
drop policy if exists "Users can update their own profile" on public.users;

create policy "Users can read their own profile"
on public.users
for select
to authenticated
using (auth.uid() = id);

create policy "Users can insert their own profile"
on public.users
for insert
to authenticated
with check (auth.uid() = id);

create policy "Users can update their own profile"
on public.users
for update
to authenticated
using (auth.uid() = id)
with check (auth.uid() = id);

drop policy if exists "Users can read their own expenses" on public.expenses;
drop policy if exists "Users can insert their own expenses" on public.expenses;
drop policy if exists "Users can update their own expenses" on public.expenses;
drop policy if exists "Users can delete their own expenses" on public.expenses;

create policy "Users can read their own expenses"
on public.expenses
for select
to authenticated
using (auth.uid() = user_id);

create policy "Users can insert their own expenses"
on public.expenses
for insert
to authenticated
with check (auth.uid() = user_id);

create policy "Users can update their own expenses"
on public.expenses
for update
to authenticated
using (auth.uid() = user_id)
with check (auth.uid() = user_id);

create policy "Users can delete their own expenses"
on public.expenses
for delete
to authenticated
using (auth.uid() = user_id);

create index if not exists expenses_user_id_date_idx
on public.expenses (user_id, expense_date desc);

drop policy if exists "Users can read their own budgets" on public.budgets;
drop policy if exists "Users can insert their own budgets" on public.budgets;
drop policy if exists "Users can update their own budgets" on public.budgets;
drop policy if exists "Users can delete their own budgets" on public.budgets;

create policy "Users can read their own budgets"
on public.budgets
for select
to authenticated
using (auth.uid() = user_id);

create policy "Users can insert their own budgets"
on public.budgets
for insert
to authenticated
with check (auth.uid() = user_id);

create policy "Users can update their own budgets"
on public.budgets
for update
to authenticated
using (auth.uid() = user_id)
with check (auth.uid() = user_id);

create policy "Users can delete their own budgets"
on public.budgets
for delete
to authenticated
using (auth.uid() = user_id);
